apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-prospectors
  namespace: {{ .Values.namespace }}
  labels:
    k8s-app: filebeat
    kubernetes.io/cluster-service: "true"
data:
  kubernetes.yml: |-
    - type: docker
      containers.ids:
      - "*"
      processors:
        - add_kubernetes_metadata:
            in_cluster: true