apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: logs-ingress
  namespace: {{ .Values.namespace }}
  labels:
    app: logs
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: 
    http:
      paths:
      - path: /
        backend:
          serviceName: kibana-logging
          servicePort: {{ .Values.kibana.port }}