apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-logging
  namespace: {{ .Values.namespace }} 
  labels:
    k8s-app: elasticsearch-logging
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    kubernetes.io/name: "Elasticsearch"
spec:
  ports:
  - port: {{ .Values.elastic.dbport }} 
    protocol: TCP
    targetPort: {{ .Values.elastic.dbport }}
  selector:
    k8s-app: elasticsearch-logging
